In [405]:
import pandas as pd
import datetime as dt
import numpy as np
import scipy.stats as stats
from sklearn.preprocessing import OneHotEncoder
from sklearn.cross_validation import train_test_split
from sklearn import linear_model
from sklearn.ensemble import RandomForestClassifier
from sklearn import ensemble
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn import cross_validation
from sklearn import preprocessing
path='D:/Project Data/Happy_Customer_Bank/'
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)
%matplotlib inline
import math

In [406]:
train=pd.read_csv(path+'Train_nyOWmfK.csv',encoding='iso-8859-1')
testdata=pd.read_csv(path+'Test_bCtAN1w.csv',encoding='iso-8859-1')
train.ix[train['Gender']=='Female','Gender_']=1
train.ix[train['Gender']=='Male','Gender_']=0
train.ix[train['Mobile_Verified']=='N','Mobile_Verified_']=0
train.ix[train['Mobile_Verified']=='Y','Mobile_Verified_']=1
train.ix[train['Filled_Form']=='Y','Filled_Form_']=1
train.ix[train['Filled_Form']=='N','Filled_Form_']=0
train.ix[train['Device_Type']=='Mobile','Device_Type_']=0
train.ix[train['Device_Type']=='Web-browser','Device_Type_']=1

train['age']=[(2015-(1900+int(i[-2:]))) for i in train['DOB'].values]  

train['Loan_Amount_Applied']=train['Loan_Amount_Applied'].fillna(train['Loan_Amount_Applied'].mean())

train['Loan_Tenure_Applied']=train['Loan_Tenure_Applied'].fillna(train['Loan_Tenure_Applied'].median())

train['Existing_EMI']=train['Existing_EMI'].fillna(0)

train['Loan_Amount_Submitted']=train['Loan_Amount_Submitted'].fillna(train['Loan_Amount_Submitted'].mean())

train['Loan_Tenure_Submitted']=train['Loan_Tenure_Submitted'].fillna(train['Loan_Tenure_Submitted'].median())

train['Interest_Rate']=train['Interest_Rate'].fillna(train['Interest_Rate'].median())

train['Processing_Fee']=train['Processing_Fee'].fillna(train['Processing_Fee'].mean())

train['EMI_Loan_Submitted']=train['EMI_Loan_Submitted'].fillna(train['EMI_Loan_Submitted'].mean())

Loan_Amount_Applied_mean=train['Loan_Amount_Applied'].mean()

Loan_Tenure_Applied_median=train['Loan_Tenure_Applied'].median()

Loan_Amount_Submitted_mean=train['Loan_Amount_Submitted'].mean()

Loan_Tenure_Submitted_median=train['Loan_Tenure_Submitted'].median()

Interest_Rate_median=train['Interest_Rate'].median()

Processing_Fee_mean=train['Processing_Fee'].mean()

EMI_Loan_Submitted_mean=train['EMI_Loan_Submitted'].mean()

In [407]:
train=train[(train['age'] < 60) | (train['Disbursed'] >=1)]
train=train[(train['Interest_Rate'] < 30) | (train['Disbursed'] >=1) ]
train=train[(train['Loan_Tenure_Applied'] > 1) | (train['Disbursed'] >=1) ]
train=train[(train['Monthly_Income'] < 600000) | (train['Monthly_Income'] > 6000)]
train=train[(train['Existing_EMI'] <= 0) | (train['Existing_EMI'] >= 1000) | (train['Disbursed'] >=1) ]
print(train.shape)
np.unique(train['Disbursed'],return_counts=True)

(46278, 31)


(array([0, 1], dtype=int64), array([45298,   980], dtype=int64))

In [408]:
train.corr()['Disbursed'].order(ascending=False)

Disbursed                1.000000
LoggedIn                 0.722839
Var5                     0.112520
Var4                     0.055444
Mobile_Verified_         0.052755
Filled_Form_             0.052652
age                      0.041927
EMI_Loan_Submitted       0.033587
Processing_Fee           0.029205
Loan_Amount_Submitted    0.024081
Loan_Amount_Applied      0.017475
Existing_EMI             0.017364
Monthly_Income           0.005569
Loan_Tenure_Submitted   -0.012904
Device_Type_            -0.014158
Loan_Tenure_Applied     -0.036166
Gender_                 -0.056377
Interest_Rate           -0.065465
Name: Disbursed, dtype: float64

In [409]:
Cat_Var=['Var4','Source','Var2','Var1']
Num_Var=[#'Monthly_Income',
    'Loan_Amount_Applied',
    'Existing_EMI',
    'Var5','Loan_Amount_Submitted',
    #'Loan_Tenure_Submitted',
      'Interest_Rate',
    'Processing_Fee',
    'EMI_Loan_Submitted']
Processed_Var=[#'Gender_',
    'Mobile_Verified_','Filled_Form_',
    #'Device_Type_',
    'age']

Target=['Disbursed']

In [410]:
cat_column=['Var4']
cat_data=train['Var4'].tolist() +testdata['Var4'].tolist()
data_=train[cat_column]
le = preprocessing.LabelEncoder()
le.fit(cat_data)
newcol=le.transform(data_)
enc = OneHotEncoder(sparse=False)
enc.fit(newcol)
print(enc.n_values_)
print(enc.feature_indices_)
dummy_var4=enc.transform(newcol)

cat_column=['Source']
cat_data=train['Source'].tolist() +testdata['Source'].tolist()
data_=train[cat_column]
le1 = preprocessing.LabelEncoder()
le1.fit(cat_data)
newcol=le1.transform(data_)
enc1 = OneHotEncoder(sparse=False)
enc1.fit(newcol)
print(enc1.n_values_)
print(enc1.feature_indices_)
dummy_Source=enc1.transform(newcol)


cat_column=['Var2']
cat_data=train['Var2'].tolist() +testdata['Var2'].tolist()
data_=train[cat_column]
le2 = preprocessing.LabelEncoder()
le2.fit(cat_data)
newcol=le2.transform(data_)
enc2 = OneHotEncoder(sparse=False)
enc2.fit(newcol)
print(enc2.n_values_)
print(enc2.feature_indices_)
dummy_var2=enc2.transform(newcol)

cat_column=['Var1']
cat_data=train['Var1'].tolist() +testdata['Var1'].tolist()
data_=train[cat_column]
le3 = preprocessing.LabelEncoder()
le3.fit(cat_data)
newcol=le3.transform(data_)
enc3 = OneHotEncoder(sparse=False)
enc3.fit(newcol)
print(enc3.n_values_)
print(enc3.feature_indices_)
dummy_var1=enc3.transform(newcol)

[8]
[0 8]
[32]
[ 0 32]
[7]
[0 7]
[19]
[ 0 19]


In [411]:
#dummy=np.hstack((dummy_var4,dummy_Source,dummy_var2,dummy_var1))
dummy=np.hstack((dummy_var4,dummy_Source,dummy_var2))
print(dummy.shape)

Num_variable=Num_Var+Processed_Var

train_num=train[Num_variable].as_matrix()
traindata=np.hstack((train_num,dummy))
traindata.shape

(46278, 41)


(46278, 51)

In [412]:
from sklearn.cross_validation import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(train[Target], 2, test_size=.99, random_state=42)
for train_index, test_index in sss:
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train_s, X_test_s = traindata[train_index], traindata[test_index]
    y_train_s, y_test_s = train[Target_log].values[train_index], train[Target_log].values[test_index]
    
print(np.unique([i[0] for i in y_train_s],return_counts=True))

X_train_s.shape, X_test_s.shape, y_train_s.shape, y_test_s.shape

(array([0, 1], dtype=int64), array([443,  19], dtype=int64))


((462, 51), (45816, 51), (462, 1), (45816, 1))

In [413]:

sampling=np.asarray([i[0] for i in target_train_1.tolist()])
sample_weights = preprocessing.balance_weights(sampling)
rfc = ensemble.GradientBoostingClassifier(n_estimators=500)
rfc.fit(X_train_s,y_train_s)
predict_class=rfc.predict(X_test_s)
print(accuracy_score(predict_class, y_test_s))
confusion_matrix(predict_class, y_test_s)
#metrics.auc(predict_class, target_test_1)

0.948664222106


C:\Anaconda3\lib\site-packages\sklearn\utils\__init__.py:93: DeprecationWarning: Function balance_weights is deprecated; balance_weights is an internal function and will be removed in 0.16
  warnings.warn(msg, category=DeprecationWarning)
C:\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1127: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[43393,  1750],
       [  602,    71]])

In [414]:
logistic = linear_model.LogisticRegression()
logistic.fit(X_train_s,y_train_s)
predict_class=logistic.predict(X_test_s)
print(accuracy_score(predict_class, y_test_s))
confusion_matrix(predict_class, y_test_s)

0.959533787323


C:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:125: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[43958,  1817],
       [   37,     4]])

In [415]:
testdata.ix[testdata['Gender']=='Female','Gender_']=1
testdata.ix[testdata['Gender']=='Male','Gender_']=0
testdata.ix[testdata['Mobile_Verified']=='N','Mobile_Verified_']=0
testdata.ix[testdata['Mobile_Verified']=='Y','Mobile_Verified_']=1
testdata.ix[testdata['Filled_Form']=='Y','Filled_Form_']=1
testdata.ix[testdata['Filled_Form']=='N','Filled_Form_']=0
testdata.ix[testdata['Device_Type']=='Mobile','Device_Type_']=0
testdata.ix[testdata['Device_Type']=='Web-browser','Device_Type_']=1

testdata['age']=[(2015-(1900+int(i[-2:]))) for i in testdata['DOB'].values]  

testdata['Loan_Amount_Applied']=testdata['Loan_Amount_Applied'].fillna(Loan_Amount_Applied_mean)

testdata['Loan_Tenure_Applied']=testdata['Loan_Tenure_Applied'].fillna(Loan_Tenure_Applied_median)

testdata['Existing_EMI']=testdata['Existing_EMI'].fillna(0)

testdata['Loan_Amount_Submitted']=testdata['Loan_Amount_Submitted'].fillna(Loan_Amount_Submitted_mean)

testdata['Loan_Tenure_Submitted']=testdata['Loan_Tenure_Submitted'].fillna(Loan_Tenure_Submitted_median)

testdata['Interest_Rate']=testdata['Interest_Rate'].fillna(Interest_Rate_median)

testdata['Processing_Fee']=testdata['Processing_Fee'].fillna(Processing_Fee_mean)

testdata['EMI_Loan_Submitted']=testdata['EMI_Loan_Submitted'].fillna(EMI_Loan_Submitted_mean)


In [416]:
cat_column=['Var4']
data_=testdata[cat_column]
newcol=le.transform(data_)
print(enc.n_values_)
print(enc.feature_indices_)
dummy_var4_test=enc.transform(newcol)

cat_column=['Source']
data_=testdata[cat_column]
newcol=le1.transform(data_)
print(enc1.n_values_)
print(enc1.feature_indices_)
dummy_Source_test=enc1.transform(newcol)

cat_column=['Var2']
data_=testdata[cat_column]
newcol=le2.transform(data_)
print(enc2.n_values_)
print(enc2.feature_indices_)
dummy_var2_test=enc2.transform(newcol)

cat_column=['Var1']
data_=testdata[cat_column]
newcol=le3.transform(data_)
print(enc3.n_values_)
print(enc3.feature_indices_)
dummy_var1_test=enc3.transform(newcol)


[8]
[0 8]
[32]
[ 0 32]
[7]
[0 7]
[19]
[ 0 19]


In [417]:
#dummy_test=np.hstack((dummy_var4_test,dummy_Source_test,dummy_var2_test,dummy_var1_test))
dummy_test=np.hstack((dummy_var4_test,dummy_Source_test,dummy_var2_test))
print(dummy_test.shape)
testdata_num=testdata[Num_variable].as_matrix()
testdata_final=np.hstack((testdata_num,dummy_test))
print(testdata_final.shape)

(37717, 41)
(37717, 51)


In [418]:
predict_class1=rfc.predict(testdata_final)
print(np.unique(predict_class1,return_counts=True))
predict_class1=predict_class1.tolist()
submis=pd.DataFrame(data={'ID':testdata['ID'],'Disbursed':predict_class1},columns=['ID','Disbursed'])
submis.to_csv(path+'submis_11.csv',index=False)

(array([0, 1], dtype=int64), array([37252,   465], dtype=int64))


In [419]:
predict_log_test=logistic.predict(testdata_final)
print(np.unique(predict_log_test,return_counts=True))
predict_log_test=predict_log_test.tolist()
sub=pd.DataFrame(data={'ID':testdata['ID'],'Disbursed':predict_log_test},columns=['ID','Disbursed'])
sub.to_csv(path+'sub_12.csv',index=False)

(array([0, 1], dtype=int64), array([37659,    58], dtype=int64))
