In [87]:
import pandas as pd
import datetime as dt
import numpy as np
import scipy.stats as stats
from sklearn.preprocessing import OneHotEncoder
from sklearn.cross_validation import train_test_split
from sklearn import linear_model
from sklearn.ensemble import RandomForestClassifier
from sklearn import ensemble
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn import cross_validation
from sklearn import preprocessing
path='D:/Project Data/Happy_Customer_Bank/'
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)
%matplotlib inline
import math

In [88]:
train=pd.read_csv(path+'Train.csv',encoding='iso-8859-1')
testdata=pd.read_csv(path+'Test.csv',encoding='iso-8859-1')
train.ix[train['Gender']=='Female','Gender_']=1
train.ix[train['Gender']=='Male','Gender_']=0
train.ix[train['Mobile_Verified']=='N','Mobile_Verified_']=0
train.ix[train['Mobile_Verified']=='Y','Mobile_Verified_']=1
train.ix[train['Filled_Form']=='Y','Filled_Form_']=1
train.ix[train['Filled_Form']=='N','Filled_Form_']=0
train.ix[train['Device_Type']=='Mobile','Device_Type_']=0
train.ix[train['Device_Type']=='Web-browser','Device_Type_']=1

train['age']=[(2015-(1900+int(i[-2:]))) for i in train['DOB'].values]  

train['Loan_Amount_Applied']=train['Loan_Amount_Applied'].fillna(train['Loan_Amount_Applied'].mean())

train['Loan_Tenure_Applied']=train['Loan_Tenure_Applied'].fillna(train['Loan_Tenure_Applied'].median())

train['Existing_EMI']=train['Existing_EMI'].fillna(0)

train['Loan_Amount_Submitted']=train['Loan_Amount_Submitted'].fillna(train['Loan_Amount_Submitted'].mean())

train['Loan_Tenure_Submitted']=train['Loan_Tenure_Submitted'].fillna(train['Loan_Tenure_Submitted'].median())

train['Interest_Rate']=train['Interest_Rate'].fillna(train['Interest_Rate'].median())

train['Processing_Fee']=train['Processing_Fee'].fillna(train['Processing_Fee'].mean())

train['EMI_Loan_Submitted']=train['EMI_Loan_Submitted'].fillna(train['EMI_Loan_Submitted'].mean())

Loan_Amount_Applied_mean=train['Loan_Amount_Applied'].mean()

Loan_Tenure_Applied_median=train['Loan_Tenure_Applied'].median()

Loan_Amount_Submitted_mean=train['Loan_Amount_Submitted'].mean()

Loan_Tenure_Submitted_median=train['Loan_Tenure_Submitted'].median()

Interest_Rate_median=train['Interest_Rate'].median()

Processing_Fee_mean=train['Processing_Fee'].mean()

EMI_Loan_Submitted_mean=train['EMI_Loan_Submitted'].mean()

In [79]:
z= np.unique(train['Source'],return_counts=True)
freq_table=pd.DataFrame({'Cat1':z[0],'value1':z[1]})
freq_table=freq_table[freq_table['value1']<600 ]
Souce_red=freq_table['Cat1'].values.tolist()

x= np.unique(train['Var1'],return_counts=True)
freq_table1=pd.DataFrame({'Cat':x[0],'value':x[1]})
freq_table1=freq_table1[freq_table1['value']<500 ]
varred=freq_table1['Cat'].values.tolist()
#print(np.unique(train['Var1']))

In [90]:
freq_table1

Cat  value
0   HAVC    384
4   HAXF     15
5   HAXM    268
7   HAZD    109
14  HCXD    237
16  HCXG     78
17  HCYS    217
18  HVYS    186

In [91]:
np.unique(train['Source'])

array(['S122', 'S123', 'S124', 'S125', 'S127', 'S129', 'S130', 'S133',
       'S134', 'S135', 'S136', 'S137', 'S138', 'S139', 'S140', 'S141',
       'S143', 'S144', 'S150', 'S151', 'S153', 'S154', 'S155', 'S156',
       'S157', 'S158', 'S159', 'S160', 'S161', 'S162'], dtype=object)

In [92]:
np.unique(train['Var1'])

array(['HAVC', 'HAXA', 'HAXB', 'HAXC', 'HAXF', 'HAXM', 'HAYT', 'HAZD',
       'HBXA', 'HBXB', 'HBXC', 'HBXD', 'HBXH', 'HBXX', 'HCXD', 'HCXF',
       'HCXG', 'HCYS', 'HVYS'], dtype=object)

In [83]:
train[train['Var1'].isin(varred)] ='Other1'
testdata[testdata['Var1'].isin(varred)] ='Other1'
train[train['Source'].isin(Souce_red)] ='Other'
testdata[testdata['Source'].isin(Souce_red)] ='Other'

In [84]:
np.unique(train['Var1'],return_counts=True)

(array(['HAXA', 'HAXB', 'HAXC', 'HAYT', 'HBXA', 'HBXB', 'HBXC', 'HBXD',
        'HBXH', 'HBXX', 'HCXF', 'Other', 'Other1'], dtype=object),
 array([ 2830,  1990,  1510,   501,  2114,  4435,  8786,  1927,   950,
        58267,   702,  1514,  1494], dtype=int64))

In [85]:
np.unique(train['Source'],return_counts=True)

(array(['Other', 'Other1', 'S122', 'S127', 'S133', 'S134', 'S137', 'S143',
        'S151', 'S157', 'S159', 'S161'], dtype=object),
 array([ 1514,  1494, 37940,  1899, 29332,  1267,  1688,  4271,   697,
          641,  5521,   756], dtype=int64))

In [89]:
train.head(10).transpose()

0                                    1  \
ID                     ID000002C20                          ID000004E40   
Gender                      Female                                 Male   
City                         Delhi                               Mumbai   
Monthly_Income               20000                                35000   
DOB                      23-May-78                            07-Oct-85   
Lead_Creation_Date       15-May-15                            04-May-15   
Loan_Amount_Applied         300000                               200000   
Loan_Tenure_Applied              5                                    2   
Existing_EMI                     0                                    0   
Employer_Name              CYBOSOL  TATA CONSULTANCY SERVICES LTD (TCS)   
Salary_Account           HDFC Bank                           ICICI Bank   
Mobile_Verified                  N                                    Y   
Var5                             0                                   13   
Var1                          HBXX                                 HBXA   
Loan_Amount_Submitted     395010.6                               200000   
Loan_Tenure_Submitted            4                                    2   
Interest_Rate                   18                                13.25   
Processing_Fee            5131.151                             5131.151   
EMI_Loan_Submitted        10999.53                               6762.9   
Filled_Form                      N                                    N   
Device_Type            Web-browser                          Web-browser   
Var2                             G                                    G   
Source                        S122                                 S122   
Var4                             1                                    3   
LoggedIn                         0                                    0   
Disbursed                        0                                    0   
Gender_                          1                                    0   
Mobile_Verified_                 0                                    1   
Filled_Form_                     0                                    0   
Device_Type_                     1                                    1   
age                             37                                   30   

                                             2                    3  \
ID                                 ID000007H20          ID000008I30   
Gender                                    Male                 Male   
City                                 Panchkula              Saharsa   
Monthly_Income                           22500                35000   
DOB                                  10-Oct-81            30-Nov-87   
Lead_Creation_Date                   19-May-15            09-May-15   
Loan_Amount_Applied                     600000              1000000   
Loan_Tenure_Applied                          4                    5   
Existing_EMI                                 0                    0   
Employer_Name          ALCHEMIST HOSPITALS LTD     BIHAR GOVERNMENT   
Salary_Account             State Bank of India  State Bank of India   
Mobile_Verified                              Y                    Y   
Var5                                         0                   10   
Var1                                      HBXX                 HBXX   
Loan_Amount_Submitted                   450000               920000   
Loan_Tenure_Submitted                        4                    5   
Interest_Rate                               18                   18   
Processing_Fee                        5131.151             5131.151   
EMI_Loan_Submitted                    10999.53             10999.53   
Filled_Form                                  N                    N   
Device_Type                        Web-browser          Web-browser   
Var2                                         B                    B   

In [73]:
print(train.shape)
train=train[(train['age'] < 60) | (train['Disbursed'] >=1)]
train=train[(train['Interest_Rate'] < 30) | (train['Disbursed'] >=1) ]
train=train[(train['Loan_Tenure_Applied'] > 1) | (train['Disbursed'] >=1) ]
train=train[(train['Monthly_Income'] < 1000000) | (train['Monthly_Income'] > 6000)]
train=train[(train['Existing_EMI'] <= 0) | (train['Existing_EMI'] >= 1000) | (train['Disbursed'] >=1) ]
print(train.shape)
np.unique(train['Disbursed'],return_counts=True)

(87020, 31)


TypeError: unorderable types: str() < int()

In [113]:
train.corr()['Disbursed'].order(ascending=False)

Disbursed                1.000000
LoggedIn                 0.749983
Var5                     0.112775
Filled_Form_             0.084977
Var4                     0.081043
Mobile_Verified_         0.076333
EMI_Loan_Submitted       0.072815
Loan_Amount_Submitted    0.069310
Processing_Fee           0.051792
age                      0.041576
Existing_EMI             0.011357
Monthly_Income           0.005193
Loan_Tenure_Submitted    0.003686
Loan_Amount_Applied     -0.016682
Gender_                 -0.076329
Interest_Rate           -0.089128
Loan_Tenure_Applied     -0.133451
Device_Type_            -0.416022
Name: Disbursed, dtype: float64

In [114]:
Cat_Var=['Var4','Source','Var2','Var1']
Num_Var=['Monthly_Income',
    #'Loan_Amount_Applied',
    #'Existing_EMI',
    'Var5',
    #     'Loan_Amount_Submitted',
    #'Loan_Tenure_Submitted',
 #'Interest_Rate',
#'Processing_Fee',
'EMI_Loan_Submitted'
        ]
Processed_Var=[#'Gender_',
    'Mobile_Verified_','Filled_Form_',
    'Device_Type_',
    'age']
Target_log=['LoggedIn']
Target=['Disbursed']

In [115]:
Num_Var_log=Num_Var +['LoggedIn']

In [116]:
cat_column=['Var4']
cat_data=train['Var4'].tolist() +testdata['Var4'].tolist()
data_=train[cat_column]
le = preprocessing.LabelEncoder()
le.fit(cat_data)
newcol=le.transform(data_)
enc = OneHotEncoder(sparse=False)
enc.fit(newcol)
print(enc.n_values_)
print(enc.feature_indices_)
dummy_var4=enc.transform(newcol)

cat_column=['Source']
cat_data=train['Source'].tolist() +testdata['Source'].tolist()
data_=train[cat_column]
le1 = preprocessing.LabelEncoder()
le1.fit(cat_data)
newcol=le1.transform(data_)
enc1 = OneHotEncoder(sparse=False)
enc1.fit(newcol)
print(enc1.n_values_)
print(enc1.feature_indices_)
dummy_Source=enc1.transform(newcol)


cat_column=['Var2']
cat_data=train['Var2'].tolist() +testdata['Var2'].tolist()
data_=train[cat_column]
le2 = preprocessing.LabelEncoder()
le2.fit(cat_data)
newcol=le2.transform(data_)
enc2 = OneHotEncoder(sparse=False)
enc2.fit(newcol)
print(enc2.n_values_)
print(enc2.feature_indices_)
dummy_var2=enc2.transform(newcol)

cat_column=['Var1']
cat_data=train['Var1'].tolist() +testdata['Var1'].tolist()
data_=train[cat_column]
le3 = preprocessing.LabelEncoder()
le3.fit(cat_data)
newcol=le3.transform(data_)
enc3 = OneHotEncoder(sparse=False)
enc3.fit(newcol)
print(enc3.n_values_)
print(enc3.feature_indices_)
dummy_var1=enc3.transform(newcol)

[8]
[0 8]
[32]
[ 0 32]
[7]
[0 7]
[19]
[ 0 19]


In [117]:
#dummy=np.hstack((dummy_var4,dummy_Source,dummy_var2,dummy_var1))
dummy=np.hstack((dummy_var4,dummy_Source,dummy_var2,dummy_var1))
print(dummy.shape)

Num_variable=Num_Var+Processed_Var

train_num=train[Num_variable].as_matrix()
traindata=np.hstack((train_num,dummy))
traindata.shape

(47065, 61)


(47065, 68)

In [118]:
from sklearn.cross_validation import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(train[Target_log], 2, test_size=.5, random_state=42)
for train_index, test_index in sss:
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train_s, X_test_s = traindata[train_index], traindata[test_index]
    y_train_s, y_test_s = train[Target_log].values[train_index], train[Target_log].values[test_index]

X_train_s.shape, X_test_s.shape, y_train_s.shape, y_test_s.shape

y_test_s=[i[0] for i in y_test_s]

# predicting login

In [119]:

rfc = ensemble.RandomForestClassifier()
rfc.fit(X_train_s,y_train_s)
predict_class=rfc.predict(X_test_s)
print(accuracy_score(predict_class, y_test_s))
confusion_matrix(predict_class, y_test_s)
#metrics.auc(predict_class, target_test_1)

0.953767050525


C:\Anaconda3\lib\site-packages\IPython\kernel\__main__.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  app.launch_new_instance()


array([[22315,   925],
       [  163,   130]])

In [120]:
logistic = linear_model.LogisticRegression()
logistic.fit(X_train_s,y_train_s)
predict_class=logistic.predict(X_test_s)
print(accuracy_score(predict_class, y_test_s))
confusion_matrix(predict_class, y_test_s)

0.955169336676


C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[22478,  1055],
       [    0,     0]])

In [121]:
bag=ensemble.BaggingClassifier(rfc)
bag.fit(X_train_s,y_train_s)
predict_class2=bag.predict(X_test_s)
print(accuracy_score(predict_class2, y_test_s))
confusion_matrix(predict_class2, y_test_s)


0.958611311775


C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[22437,   933],
       [   41,   122]])

In [122]:
bag_=ensemble.RandomForestClassifier(max_depth=4)
bag_.fit(X_train_s,y_train_s)
predict_class2=bag_.predict(X_test_s)
print(accuracy_score(predict_class2, y_test_s))
confusion_matrix(predict_class2, y_test_s)


0.959588662729


C:\Anaconda3\lib\site-packages\IPython\kernel\__main__.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  from IPython.kernel.zmq import kernelapp as app


array([[22472,   945],
       [    6,   110]])

# predicting disb

In [123]:
Numerical_var= Num_Var_log+Processed_Var

train_log=train[Numerical_var].as_matrix()
traindata_log=np.hstack((train_log,dummy))
traindata_log.shape

(47065, 69)

In [124]:
sss1 = StratifiedShuffleSplit(train[Target], 2, test_size=.5, random_state=42)
for train_index1, test_index1 in sss1:
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train_log, X_test_log = traindata_log[train_index1], traindata_log[test_index1]
    y_train_log, y_test_log = train[Target].values[train_index1], train[Target].values[test_index1]

In [125]:
rfc_ = ensemble.RandomForestClassifier()
rfc_.fit(X_train_log,y_train_log)
predict_log=rfc_.predict(X_test_log)
print(accuracy_score(predict_log, y_test_log))
confusion_matrix(predict_log, y_test_log)

0.981642799473


C:\Anaconda3\lib\site-packages\IPython\kernel\__main__.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  from IPython.kernel.zmq import kernelapp as app


array([[22739,   275],
       [  157,   362]])

In [126]:
logistic1 = linear_model.LogisticRegression()
logistic1.fit(X_train_log,y_train_log)
predict_log=logistic1.predict(X_test_log)
print(accuracy_score(predict_log, y_test_log))
confusion_matrix(predict_log, y_test_log)

0.972931627927


C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[22896,   637],
       [    0,     0]])

In [127]:
bag2=ensemble.BaggingClassifier(rfc_)
bag2.fit(X_train_log,y_train_log)
predict_log_=bag2.predict(X_test_log)
print(accuracy_score(predict_log_, y_test_log))
confusion_matrix(predict_log_, y_test_log)

0.982365189309


C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[22741,   260],
       [  155,   377]])

In [128]:
bag2_=ensemble.RandomForestClassifier(max_depth=4)
bag2_.fit(X_train_log,y_train_log)
predict_log_=bag2_.predict(X_test_log)
print(accuracy_score(predict_log_, y_test_log))
confusion_matrix(predict_log_, y_test_log)

0.977860876216


C:\Anaconda3\lib\site-packages\IPython\kernel\__main__.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  from IPython.kernel.zmq import kernelapp as app


array([[22895,   520],
       [    1,   117]])

In [129]:
name='rf-log-bag-rf-rf4_prob'

# test datset

In [130]:
testdata.ix[testdata['Gender']=='Female','Gender_']=1
testdata.ix[testdata['Gender']=='Male','Gender_']=0
testdata.ix[testdata['Mobile_Verified']=='N','Mobile_Verified_']=0
testdata.ix[testdata['Mobile_Verified']=='Y','Mobile_Verified_']=1
testdata.ix[testdata['Filled_Form']=='Y','Filled_Form_']=1
testdata.ix[testdata['Filled_Form']=='N','Filled_Form_']=0
testdata.ix[testdata['Device_Type']=='Mobile','Device_Type_']=0
testdata.ix[testdata['Device_Type']=='Web-browser','Device_Type_']=1

testdata['age']=[(2015-(1900+int(i[-2:]))) for i in testdata['DOB'].values]  

testdata['Loan_Amount_Applied']=testdata['Loan_Amount_Applied'].fillna(Loan_Amount_Applied_mean)

testdata['Loan_Tenure_Applied']=testdata['Loan_Tenure_Applied'].fillna(Loan_Tenure_Applied_median)

testdata['Existing_EMI']=testdata['Existing_EMI'].fillna(0)

testdata['Loan_Amount_Submitted']=testdata['Loan_Amount_Submitted'].fillna(Loan_Amount_Submitted_mean)

testdata['Loan_Tenure_Submitted']=testdata['Loan_Tenure_Submitted'].fillna(Loan_Tenure_Submitted_median)

testdata['Interest_Rate']=testdata['Interest_Rate'].fillna(Interest_Rate_median)

testdata['Processing_Fee']=testdata['Processing_Fee'].fillna(Processing_Fee_mean)

testdata['EMI_Loan_Submitted']=testdata['EMI_Loan_Submitted'].fillna(EMI_Loan_Submitted_mean)


In [131]:
cat_column=['Var4']
data_=testdata[cat_column]
newcol=le.transform(data_)
print(enc.n_values_)
print(enc.feature_indices_)
dummy_var4_test=enc.transform(newcol)

cat_column=['Source']
data_=testdata[cat_column]
newcol=le1.transform(data_)
print(enc1.n_values_)
print(enc1.feature_indices_)
dummy_Source_test=enc1.transform(newcol)

cat_column=['Var2']
data_=testdata[cat_column]
newcol=le2.transform(data_)
print(enc2.n_values_)
print(enc2.feature_indices_)
dummy_var2_test=enc2.transform(newcol)

cat_column=['Var1']
data_=testdata[cat_column]
newcol=le3.transform(data_)
print(enc3.n_values_)
print(enc3.feature_indices_)
dummy_var1_test=enc3.transform(newcol)


[8]
[0 8]
[32]
[ 0 32]
[7]
[0 7]
[19]
[ 0 19]


In [132]:
#dummy_test=np.hstack((dummy_var4_test,dummy_Source_test,dummy_var2_test,dummy_var1_test))
dummy_test=np.hstack((dummy_var4_test,dummy_Source_test,dummy_var2_test,dummy_var1_test))
print(dummy_test.shape)
testdata_num=testdata[Num_variable].as_matrix()
testdata_final=np.hstack((testdata_num,dummy_test))
testdata_final.shape

(37717, 61)


(37717, 68)

In [133]:
predict_class_test=logistic.predict(testdata_final)
np.unique(predict_class_test, return_counts=True)
predict_class_test=[[i] for i in predict_class_test]


predict_ense_test=rfc.predict(testdata_final)
np.unique(predict_ense_test, return_counts=True)
predict_ense_test=[[i] for i in predict_ense_test]

predict_bag_test=bag.predict(testdata_final)
np.unique(predict_bag_test, return_counts=True)
predict_bag_test=[[i] for i in predict_bag_test]

predict_bag2_test=bag_.predict(testdata_final)
np.unique(predict_bag2_test, return_counts=True)
predict_bag2_test=[[i] for i in predict_bag2_test]

In [134]:
testdata_full_final=np.hstack((testdata_final,predict_class_test))
testdata_full_final.shape

predict_log_test=logistic1.predict_proba(testdata_full_final)
predict_log_test=predict_log_test[:,1].tolist()
#print(np.unique(predict_log_test,return_counts=True))
sub=pd.DataFrame(data={'ID':testdata['ID'],'Disbursed':predict_log_test},columns=['ID','Disbursed'])
#sub.to_csv(path+'sub13.csv',index=False)

In [135]:
testdata_full_final=np.hstack((testdata_final,predict_ense_test))
testdata_full_final.shape

predict_log_test_=rfc_.predict_proba(testdata_full_final)
predict_log_test_=predict_log_test_[:,1].tolist()
#print(np.unique(predict_log_test_,return_counts=True))
sub1=pd.DataFrame(data={'ID':testdata['ID'],'Disbursed':predict_log_test_},columns=['ID','Disbursed'])
#sub1.to_csv(path+'ense_sub13.csv',index=False)

In [136]:
testdata_full_final=np.hstack((testdata_final,predict_bag_test))
testdata_full_final.shape

predict_log_test_1=bag2.predict_proba(testdata_full_final)
predict_log_test_1=predict_log_test_1[:,1].tolist()
#print(np.unique(predict_log_test_1,return_counts=True))
sub2=pd.DataFrame(data={'ID':testdata['ID'],'Disbursed':predict_log_test_1},columns=['ID','Disbursed'])
#sub2.to_csv(path+'bag_sub13.csv',index=False)

In [137]:
testdata_full_final=np.hstack((testdata_final,predict_bag2_test))
testdata_full_final.shape

predict_log_test_1=bag2_.predict_proba(testdata_full_final)
predict_log_test_1=predict_log_test_1[:,1].tolist()
#print(np.unique(predict_log_test_1,return_counts=True))
sub2_=pd.DataFrame(data={'ID':testdata['ID'],'Disbursed':predict_log_test_1},columns=['ID','Disbursed'])
#sub2.to_csv(path+'bag_sub13.csv',index=False)

In [138]:
submission=pd.merge(pd.merge(pd.merge(sub,sub1,how='inner', on='ID'),sub2,how='inner', on='ID'),sub2_,how='inner', on='ID')

In [139]:
submission.columns

Index(['ID', 'Disbursed_x', 'Disbursed_y', 'Disbursed_x', 'Disbursed_y'], dtype='object')

In [140]:
submission['max']=submission[['Disbursed_x', 'Disbursed_y', 'Disbursed_x', 'Disbursed_y']].mean(axis=1)

In [141]:
submission.head()

ID  Disbursed_x  Disbursed_y  Disbursed_x  Disbursed_y       max
0  ID000026A10     0.396147          0.4         0.34     0.258224  0.348593
1  ID000054C40     0.263470          0.4         0.35     0.304349  0.329455
2  ID000066O10     0.235502          0.2         0.05     0.010194  0.123924
3  ID000110G00     0.239985          0.2         0.03     0.007171  0.119289
4  ID000113J30     0.235755          0.5         0.35     0.316337  0.350523

In [142]:
submission1=pd.DataFrame(data={'ID': testdata['ID'],'Disbursed':submission['max']},columns=['ID','Disbursed'])
submission1.to_csv(path+name+'.csv',index=False)